[tox]
envlist = py
skipsdist = true
skip_missing_interpreters = true

[testenv]
basepython = python3
package = skip
allowlist_externals = bash
passenv =
    HOME
    LSST_*
    EUPS_*
    PATH
    PYTHONPATH
    STACK_DIR
    TESTDATA_NICKEL_DIR
commands =
    bash -lc './scripts/with-stack.sh -S "{env:STACK_DIR:/opt/lsst/software/stack}" --setup-testdata -- pytest -q'
