# tox.ini
[tox]
envlist = py
skipsdist = true
requires = tox>=4

[testenv]
package = skip
# only the env we actually need at runtime
passenv = STACK_DIR TESTDATA_NICKEL_DIR
allowlist_externals = ./scripts/with-stack.sh
commands =
    ./scripts/with-stack.sh -S "{env:STACK_DIR:/opt/lsst/software/stack}" --setup-testdata -- pytest -q
