# Auto-generated by make_synthetic_colorterms.py
from lsst.pipe.tasks.colorterms import Colorterm, ColortermDict

config.data = {
    # PS1 -> Nickel B/V/R/I color terms. Empirically fit against Landolt standard
    # stars (2026-06-25, 10 stars from scripts/config/landolt_validation), replacing
    # the original synthetic fit. The synthetic I slope (c1=1.032) was badly wrong;
    # the Landolt fit (c1=0.352) cut I-band residual RMS 3x (0.22 -> 0.08 mag), and
    # its zeropoint c0=-0.379 independently matches Tonry+2012 I_C - i_P1 = -0.366.
    # c0 is absorbed by the per-visit photometric zeropoint in calibrateImage; the
    # c1 (color) slope is what removes color-dependent systematics. Refit with more
    # Landolt nights/fields to tighten further.
    "ps1*": ColortermDict(
        data={
            "B": Colorterm(
                primary="gMeanPSFMag",
                secondary="rMeanPSFMag",
                c0=0.215,
                c1=0.589,
                c2=0.0,
            ),
            "V": Colorterm(
                primary="gMeanPSFMag",
                secondary="rMeanPSFMag",
                c0=-0.011,
                c1=-0.540,
                c2=0.0,
            ),
            "R": Colorterm(
                primary="rMeanPSFMag",
                secondary="iMeanPSFMag",
                c0=-0.180,
                c1=-0.243,
                c2=0.0,
            ),
            "I": Colorterm(
                primary="iMeanPSFMag",
                secondary="rMeanPSFMag",
                c0=-0.379,
                c1=0.352,
                c2=0.0,
            ),
        }
    ),
    "gaia*": ColortermDict(
        data={
            "B": Colorterm(
                primary="phot_bp_mean",
                secondary="phot_rp_mean",
                c0=0.0,
                c1=0.446276,
                c2=0.0,
            ),
            "V": Colorterm(
                primary="phot_g_mean",
                secondary="phot_rp_mean",
                c0=0.0,
                c1=0.923294,
                c2=0.0,
            ),
            "R": Colorterm(
                primary="phot_rp_mean",
                secondary="phot_bp_mean",
                c0=0.0,
                c1=-0.517519,
                c2=0.0,
            ),
            "I": Colorterm(
                primary="phot_rp_mean",
                secondary="phot_bp_mean",
                c0=0.0,
                c1=0.367222,
                c2=0.0,
            ),
        }
    ),
    "*monster*": ColortermDict(
        data={
            "B": Colorterm(
                primary="monster_ComCam_g",
                secondary="monster_ComCam_r",
                c0=0.0606,
                c1=-0.1078,
                c2=0.0,
            ),
            "V": Colorterm(
                primary="monster_ComCam_g",
                secondary="monster_ComCam_r",
                c0=0.1685,
                c1=-0.4116,
                c2=0.0,
            ),
            "R": Colorterm(
                primary="monster_ComCam_r",
                secondary="monster_ComCam_i",
                c0=0.0148,
                c1=-0.101,
                c2=0.0,
            ),
            "I": Colorterm(
                primary="monster_ComCam_i",
                secondary="monster_ComCam_r",
                c0=0.0665,
                c1=0.2159,
                c2=0.0,
            ),
            # Sloan-like filters (approximate: treat as close to LSST g/r)
            "gp": Colorterm(
                primary="monster_ComCam_g",
                secondary="monster_ComCam_r",
                c0=0.0,
                c1=0.0,
                c2=0.0,
            ),
            "rp": Colorterm(
                primary="monster_ComCam_r",
                secondary="monster_ComCam_i",
                c0=0.0,
                c1=0.0,
                c2=0.0,
            ),
            # Narrowband (identity — broadband calibration is approximate)
            "Halpha": Colorterm(
                primary="monster_ComCam_r",
                secondary="monster_ComCam_i",
                c0=0.0,
                c1=0.0,
                c2=0.0,
            ),
            "OIII": Colorterm(
                primary="monster_ComCam_g",
                secondary="monster_ComCam_r",
                c0=0.0,
                c1=0.0,
                c2=0.0,
            ),
            # "B": Colorterm(
            #     primary="monster_ComCam_g",
            #     secondary="monster_ComCam_r",
            #     c0=0.0,
            #     c1=0.617608,
            #     c2=0.0,
            # ),
            # "V": Colorterm(
            #     primary="monster_ComCam_g",
            #     secondary="monster_ComCam_r",
            #     c0=0.0,
            #     c1=-0.428548,
            #     c2=0.0,
            # ),
            # "R": Colorterm(
            #     primary="monster_ComCam_r",
            #     secondary="monster_ComCam_i",
            #     c0=0.0,
            #     c1=-0.129111,
            #     c2=0.0,
            # ),
            # "I": Colorterm(
            #     primary="monster_ComCam_i",
            #     secondary="monster_ComCam_r",
            #     c0=0.0,
            #     c1=1.031936,
            #     c2=0.0,
            # ),
            # data={
            #     # Nickel filter -> MONSTER band used as primary magnitude
            #     "B": Colorterm(
            #         primary="g",
            #         secondary="r",
            #         c0=0.0,
            #         c1=0.617608,
            #         c2=0.0,
            #     ),
            #     "V": Colorterm(
            #         primary="g",
            #         secondary="r",
            #         c0=0.0,
            #         c1=-0.428548,
            #         c2=0.0,
            #     ),
            #     "R": Colorterm(
            #         primary="r",
            #         secondary="i",
            #         c0=0.0,
            #         c1=-0.129111,
            #         c2=0.0,
            #     ),
            #     "I": Colorterm(
            #         primary="i",
            #         secondary="r",
            #         c0=0.0,
            #         c1=1.031936,
            #         c2=0.0,
            #     ),
            #     # add z/y later if you ingest them:
            #     # "Z": Colorterm(primary="z", c0=0.0, c1=0.0, c2=0.0),
            #     # "Y": Colorterm(primary="y", c0=0.0, c1=0.0, c2=0.0),
        }
    ),
}
# ruff: noqa: F821
