object: "2023ixf"
# Science reference nights (earlier 2023 observations during SN peak/plateau)
nights:
  20230519:
    b: []
    v: []
    r: []
    i: []
  20230521:
    b: []
    v: []
    r: []
    i: []
  20230523:
    b: []
    v: []
    r: []
    i: []
  20230527:
    b: []
    v: []
    r: []
    i: []
  20230531:
    b: []
    v: []
    r: []
    i: []
  20230602:
    b: []
    v: []
    r: []
    i: []
  20230608:
    b: []
    v: []
    r: []
    i: []
  20230611:
    b: []
    v: []
    r: []
    i: []
  20230616:
    b: []
    v: []
    r: []
    i: []
  20230618:
    b: []
    v: []
    r: []
    i: []
  20230625:
    b: []
    v: []
    r: []
    i: []
  20230629:
    b: []
    v: []
    r: []
    i: []
  20230703:
    b: []
    v: []
    r: []
    i: []
  20230706:
    b: []
    v: []
    r: []
    i: []
  20230709:
    b: []
    v: []
    r: []
    i: []
