#!/usr/bin/env bash
#
# build_nights_reference.sh - Build a reference table from observing nights
#
# Converts a simple list of observing nights into a detailed reference YAML
# that includes actual Butler day_obs values, visit IDs, and metadata.
#
# Usage:
#   ./build_nights_reference.sh --object TARGET --nights NIGHTS_FILE --output YAML_FILE
#
# Example:
#   ./build_nights_reference.sh \
#     --object 2020wnt \
#     --nights scripts/config/2020wnt/sn_nights.txt \
#     --output scripts/config/2020wnt/nights_reference.yaml
#

set -euo pipefail

OBJECT=""
NIGHTS_FILE=""
OUTPUT_FILE=""
BANDS_FILTER=""

usage() {
  cat <<USAGE
Usage: $0 --object TARGET --nights NIGHTS_FILE --output OUTPUT_FILE [OPTIONS]

Build a reference table from observing nights by querying Butler for metadata.

Required Arguments:
  --object TARGET       Target name (e.g., '2020wnt')
  --nights NIGHTS_FILE  File with observing nights (YYYYMMDD, one per line)
  --output OUTPUT_FILE  Output YAML file path

Optional Arguments:
  --bands BANDS         Comma-separated bands to include (default: all)
  -h, --help            Show this help

Example:
  $0 \\
    --object 2020wnt \\
    --nights scripts/config/2020wnt/sn_nights.txt \\
    --output scripts/config/2020wnt/nights_reference.yaml

USAGE
  exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --object) OBJECT="$2"; shift 2;;
    --nights) NIGHTS_FILE="$2"; shift 2;;
    --output) OUTPUT_FILE="$2"; shift 2;;
    --bands) BANDS_FILTER="$2"; shift 2;;
    -h|--help) usage;;
    *) echo "ERROR: Unknown argument: $1"; usage;;
  esac
done

# Validate arguments
[[ -z "$OBJECT" ]] && { echo "ERROR: --object required"; usage; }
[[ -z "$NIGHTS_FILE" ]] && { echo "ERROR: --nights required"; usage; }
[[ -z "$OUTPUT_FILE" ]] && { echo "ERROR: --output required"; usage; }
[[ ! -f "$NIGHTS_FILE" ]] && { echo "ERROR: Nights file not found: $NIGHTS_FILE"; exit 1; }
[[ -z "${REPO:-}" ]] && { echo "ERROR: REPO not set. Source your .env file first."; exit 1; }

# Check that butler command is available and get its path
BUTLER_CMD=$(command -v butler 2>/dev/null)
if [[ -z "$BUTLER_CMD" ]]; then
  echo "ERROR: butler command not found."
  echo "Load the LSST environment first:"
  echo "  source /Users/dangause/Developer/lick/lsst/lsst_stack/loadLSST.bash"
  echo "  setup lsst_distrib"
  exit 1
fi

# Find the obs_nickel scripts directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OBS_NICKEL_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Read nights from file (strip leading/trailing whitespace but preserve newlines)
readarray -t OBSERVING_NIGHTS < <(grep -v '^#' "$NIGHTS_FILE" | grep -v '^[[:space:]]*$' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

if [[ ${#OBSERVING_NIGHTS[@]} -eq 0 ]]; then
  echo "ERROR: No nights found in $NIGHTS_FILE"
  exit 1
fi

echo "Building reference table for ${#OBSERVING_NIGHTS[@]} observing nights..."
echo "Target: $OBJECT"
echo "Repository: $REPO"
echo ""

# Create output directory if needed
OUTPUT_DIR=$(dirname "$OUTPUT_FILE")
mkdir -p "$OUTPUT_DIR"

# Write YAML header
cat > "$OUTPUT_FILE" <<HEADER
# Auto-generated by build_nights_reference.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Source: $NIGHTS_FILE
# Target: $OBJECT
# Repository: $REPO

object: "$OBJECT"
nights:
HEADER

# Process each observing night
for OBS_NIGHT in "${OBSERVING_NIGHTS[@]}"; do
  echo "Processing observing night $OBS_NIGHT..."

  # Try both the observing night and next day (for timezone issues)
  if [[ "$OSTYPE" == "darwin"* ]]; then
    NEXT_DAY=$(date -j -v+1d -f "%Y%m%d" "$OBS_NIGHT" "+%Y%m%d" 2>/dev/null || echo "")
  else
    NEXT_DAY=$(date -d "$OBS_NIGHT + 1 day" "+%Y%m%d" 2>/dev/null || echo "")
  fi

  FOUND_DATA=false
  ACTUAL_DAY_OBS=""

  for UT_DATE in "$OBS_NIGHT" "$NEXT_DAY"; do
    [[ -z "$UT_DATE" ]] && continue

    # Query Butler for exposures on this day_obs
    WHERE="instrument='Nickel' AND exposure.day_obs=${UT_DATE} AND exposure.target_name='${OBJECT}'"

    # Get exposure data from Butler using full path
    EXPOSURE_DATA=$("$BUTLER_CMD" query-dimension-records "$REPO" exposure --where "$WHERE" 2>&1 | grep "^[[:space:]]*Nickel" || true)

    # Check if we found any data
    if [[ -n "$EXPOSURE_DATA" ]]; then
      FOUND_DATA=true
      ACTUAL_DAY_OBS="$UT_DATE"

      # Parse the exposure data
      # Format: instrument id day_obs ... physical_filter ...
      VISIT_IDS=$(echo "$EXPOSURE_DATA" | awk '{print $2}' | sort -n | tr '\n' ',' | sed 's/,$//')
      BANDS=$(echo "$EXPOSURE_DATA" | awk '{print $9}' | sort -u | tr '\n' ',' | sed 's/,$//')
      EXPOSURE_COUNT=$(echo "$EXPOSURE_DATA" | wc -l | tr -d ' ')

      break
    fi
  done

  if [[ "$FOUND_DATA" == "false" ]]; then
    # No data found for this night
    cat >> "$OUTPUT_FILE" <<NIGHT_ENTRY
  - obs_night: $OBS_NIGHT
    day_obs: null
    error: "No exposures found for target $OBJECT"
    visits: []
    bands: []

NIGHT_ENTRY
    echo "  ⚠ No data found for $OBS_NIGHT"
    continue
  fi

  # Apply bands filter if specified
  if [[ -n "$BANDS_FILTER" ]]; then
    FILTERED_BANDS=""
    IFS=',' read -ra AVAILABLE_BANDS <<< "$BANDS"
    IFS=',' read -ra REQUESTED_BANDS <<< "$BANDS_FILTER"

    for band in "${REQUESTED_BANDS[@]}"; do
      for avail_band in "${AVAILABLE_BANDS[@]}"; do
        if [[ "$band" == "$avail_band" ]]; then
          FILTERED_BANDS="${FILTERED_BANDS:+$FILTERED_BANDS,}$band"
        fi
      done
    done
    BANDS="$FILTERED_BANDS"
  fi

  # Write night entry to YAML
  cat >> "$OUTPUT_FILE" <<NIGHT_ENTRY
  - obs_night: $OBS_NIGHT
    day_obs: $ACTUAL_DAY_OBS
    visits: [$VISIT_IDS]
    bands: [$BANDS]
    exposure_count: $EXPOSURE_COUNT

NIGHT_ENTRY

  echo "  ✓ Found $EXPOSURE_COUNT exposures on day_obs=$ACTUAL_DAY_OBS, bands=[$BANDS]"
done

echo ""
echo "✓ Reference table created: $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "  1. Review the reference file and edit if needed (exclude bad visits, add notes)"
echo "  2. Use with run_dia_multi_band.sh:"
echo "     ./scripts/pipeline/run_dia_multi_band.sh \\"
echo "       --science-reference $OUTPUT_FILE \\"
echo "       --ra <RA> --dec <DEC> --object $OBJECT ..."
