# Auto-generated by make_synthetic_colorterms.py
from lsst.pipe.tasks.colorterms import Colorterm, ColortermDict

config.data = {
    "panstarrs1*": ColortermDict(
        data={
            "B": Colorterm(
                primary="gMeanPSFMag",
                secondary="rMeanPSFMag",
                c0=0.0,
                c1=0.617608,
                c2=0.0,
            ),
            "V": Colorterm(
                primary="gMeanPSFMag",
                secondary="rMeanPSFMag",
                c0=0.0,
                c1=-0.428548,
                c2=0.0,
            ),
            "R": Colorterm(
                primary="rMeanPSFMag",
                secondary="iMeanPSFMag",
                c0=0.0,
                c1=-0.129111,
                c2=0.0,
            ),
            "I": Colorterm(
                primary="iMeanPSFMag",
                secondary="rMeanPSFMag",
                c0=0.0,
                c1=1.031936,
                c2=0.0,
            ),
        }
    ),
    "gaia*": ColortermDict(
        data={
            "B": Colorterm(
                primary="phot_bp_mean_mag",
                secondary="phot_rp_mean_mag",
                c0=0.0,
                c1=0.446276,
                c2=0.0,
            ),
            "V": Colorterm(
                primary="phot_g_mean_mag",
                secondary="phot_rp_mean_mag",
                c0=0.0,
                c1=0.923294,
                c2=0.0,
            ),
            "R": Colorterm(
                primary="phot_rp_mean_mag",
                secondary="phot_bp_mean_mag",
                c0=0.0,
                c1=-0.517519,
                c2=0.0,
            ),
            "I": Colorterm(
                primary="phot_rp_mean_mag",
                secondary="phot_bp_mean_mag",
                c0=0.0,
                c1=0.367222,
                c2=0.0,
            ),
        }
    ),
}
